FROM openjdk:10
WORKDIR usr/src
ADD ./target/kafkaproducerdemo-0.0.1-SNAPSHOT.jar /usr/src/kafkaproducerdemo-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "/usr/src/kafkaproducerdemo-0.0.1-SNAPSHOT.jar"]
